# -*- coding: utf-8 -*-
"""multi_variable_linear_regression_using_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zqyRnbfrFVTd9Z6X_mS6E2FPpDkG8guk

Import Modules
"""

import numpy as np
from sklearn.linear_model import LinearRegression

"""Data"""

x1=np.array([73, 93, 89, 96, 73, 53, 69, 47, 87, 79, 69, 70, 93, 79, 70, 93, 78, 81, 88, 78])
x1=x1.reshape((20, 1))
x2=np.array([80, 88, 91, 98, 66, 46, 74, 56, 79, 70, 70, 65, 95, 80, 73, 89, 75, 90, 92, 83])
x2=x2.reshape((20, 1))
x3=np.array([75, 93, 90, 100, 70, 55, 77, 60, 90, 88, 73, 74, 91, 73, 78, 96, 68, 93, 86, 77])
x3=x3.reshape((20, 1))
y=np.array([152, 185, 180, 196, 142, 101, 149, 115, 175, 164, 141, 141, 184, 152, 148, 192, 147, 183, 177, 159])
y=y.reshape((20, 1))
X=np.concatenate([x1, x2], axis=1)
X=np.concatenate([X, x3], axis=1)

"""Setting Model"""

model=LinearRegression()
model.fit(X, y)

"""print weight and bias"""

print(model.coef_)

"""Accuracy"""

print(model.score(X, y))

"""Predict value for (100, 90, 80)"""

test_data=np.array([[100, 90, 80]])
print(model.predict(test_data))